---

### Configure FTP

# Host to connect to, e.g. ftp.example.com. Do not include the protocol
ftp_host: "ftp.example.com"

# Setting ftp_debug to 1 will give a lot of information about the FTP 
# session. You probably do not want to use this in production
# Options:
#     0 = be quiet
#     1 = show debug output
ftp_debug: 0

# Username and password for logging into the FTP server
ftp_user: "anonymous"
ftp_pass: "pass"

# Path on the FTP server where the file we are looking for can be found
ftp_path: "/path/to/file/"

# Filename for the file we are looking for on the server
# The filename is worked out using the DateTime Perl module, which means it
# can contain "variables" related to year, month, date etc. 
# See https://metacpan.org/pod/DateTime#strftime-Patterns for a full list
# of variables. 
# 
# Example: "MyLib.%Y%m%d.marc" -> "MyLib.20150323.marc"
# 
ftp_file: "MyLib.%Y%m%d.marc"

# Number of hours that should be subtracted from the time at which the script
# is run, in order to calculate the date part of the filename above.
# Example: A new file is published at 2am each night, but the date part of the
# filename is for the day before the current day. So the file published on
# 2015-03-24 has 2015-03-23 (in some form) as the date part of the filename.
# Set this variable to 24 to account for this.
# If files are dated to the same date they are published, just leave this as 0.
subtract_hours: 0

# Where do you want to store the downloaded file? Include trailing slash! 
local_dir: "/tmp/"

# Delete the downloaded file after it has been imported? 
# Options:
#     1 = yes, delete the file
#     0 = no, keep the file
cleanup: 1

### Local Koha instance

# Code for the framework the records should be imported with
frameworkcode: ""

### Special item values

# Look for 'text' in 'field' and 'subfield'

special_items: 
 - field: 245
   subfield: h
   text: "Electronic resource"
   952a: 'Y'
   952b: 'Y'
   952y: 'EBOOK'
   9527: '0' # Zero is "available"

### Default item values

952a: 'ONORDER' # Homebranch
952b: 'ONORDER' # Holdingbranch
952y: 'ONORDER' # Item type
9527: '-1' # -1 is "On order", but avaialable for holds
