---

### Configure FTP

# Host to connect to, e.g. ftp.example.com. Do not include the protocol
ftp_host: "ftp.example.com"

# Setting ftp_debug to 1 will give a lot of information about the FTP 
# session. You probably do not want to use this in production
# Options:
#     0 = be quiet
#     1 = show debug output
ftp_debug: 0

# Username and password for logging into the FTP server
ftp_user: "anonymous"
ftp_pass: "pass"

# Path on the FTP server where the file we are looking for can be found
ftp_path: "/path/to/file/"

# Filename for the file we are looking for on the server
# The filename is worked out using the DateTime Perl module, which means it
# can contain "variables" related to year, month, date etc. 
# See https://metacpan.org/pod/DateTime#strftime-Patterns for a full list
# of variables. 
# 
# Example: "MyLib.%Y%m%d.marc" -> "MyLib.20150323.marc"
# 
ftp_file: "MyLib.%Y%m%d.marc"

# Expected format of incoming files. Possible values:
# - marc (ISO2709)
# - marcxml
marc_format: xml

# Number of hours that should be subtracted from the time at which the script
# is run, in order to calculate the date part of the filename above.
# Example: A new file is published at 2am each night, but the date part of the
# filename is for the day before the current day. So the file published on
# 2015-03-24 has 2015-03-23 (in some form) as the date part of the filename.
# Set this variable to 24 to account for this.
# If files are dated to the same date they are published, just leave this as 0.
subtract_hours: 0

# Where do you want to store the downloaded file? Include trailing slash! 
local_dir: "/tmp/"

# Delete the downloaded file after it has been imported? 
# Options:
#     1 = yes, delete the file
#     0 = no, keep the file
cleanup: 1

# If matching on 001+003 fails, we can optionally fall back to matching on only
# 001.
fallback_to_001_matching: 0

# If this is set to one, matching on ISBN will be done if matching on 001/003
# fails. In order to give a match, there must be one 020-field that is identical
# in both records, that means they must have exactly the same subfields with
# exactly the same values.
match_on_isbn: 1

# Define fields whose content could make us skip records outright. We need to
# define a field, a subfield and some text that might be contained in the
# given subfield. The record will be skipped if one field/subfield has a match,
# so there is an implied OR between the fields, not an AND.
skip_records:
  - field: 245
    subfield: h
    contains: "Elektronisk resurs"

# Fields that should be deleted from the incoming record
delete_fields:
  - field: 010
  - field: 013
  - field: 015
  - field: 016
  - field: 017
  - field: 030
  - field: 032
  - field: 033
  - field: 034
  - field: 036

# Go through all fields with the given field number. If there is a subfield with
# the given code, and that subfield contains the given text, do not import the
# field. Matching on text considers the whole field (not substrings), and is
# not case sensitive.
delete_fields_on_content:
  - field: 650
    subfield: 2
    contains: qlit

# Fields that sould be preserved (copied from the record in Koha to the incoming
# record, replacing any fields of the same code in the incoming record). You
# probably want to have at least 942 in this list, since this is a Koha specific
# field that should not be removed or overwritten by anything from the external source.
preserve_fields:
  - 942
  - 562
  - 590
  - 591
  - 592
  - 593
  - 594
  - 595
  - 596
  - 597
  - 598
  - 697
  - 599
  - 653
  - 852
  - 976

# Remove 852 fields where the value of 852b is not in the list below. The value
# on right of the colon should always be 1, for convenience.
filter_on_852b:
  A: 1
  X: 1

# Add fields to both new and old records (if the field does not already exist)
add_fields:
  - field: 942
    subfields:
      c: BOK

# Add item subfields based on fields in the record. This example will create
# 952$z, with a value concatenated from all 852$x fields in the record. If there
# are multiple 852$x, they will be separated by the "delimiter" string.
# In other words, this will take info from the record's "recordfield" and
# "recordsubfield" and put it in the "itemfield" subfield of 952s in the Koha
# record.
# Remember to include spacing in the "delimiter". If "delimiter" is given as
# "|", the result will be "a|b".
item_values_from_record:
  - itemfield: z
    item_db_field: itemnotes
    recordfield: 852
    recordsubfield: x
    delimiter: " | "

# Values 1 | 0
# Update items based on the mapping in item_values_from_record when updated
# records are received.
update_item_values_from_record: 1

### Local Koha instance

# Code for the framework the records should be imported with.
# Leave empty (frameworkcode: "") to use the default framework.
frameworkcode: ""

### Special item values

# Look for 'text' in 'field' and 'subfield'

special_items: 
 - field: 245
   subfield: h
   text: "Electronic resource"
   952a: 'Y'
   952b: 'Y'
   952c: 'X' # Shelving location code. LOC
   952y: 'EBOOK'
   9527: '0' # Zero is "available"
   9528: 'Z'  # Collection code. CCODE
   952o: 'Elektronisk tilgang' # Koha full call number
 - field: 008
   position: 22
   text: j
   952a: 'Y'
   952b: 'Y'
   952c: 'CHILD' # Shelving location code. LOC
   952y: 'BOOK'
   9527: '0' # Zero is "available"
   9528: 'CHILD'  # Collection code. CCODE
   952o: 'Barneavdelingen' # Koha full call number

### Default item values

952a: 'ONORDER' # Homebranch
952b: 'ONORDER' # Holdingbranch
952c: 'X' # Shelving location code. LOC
952y: 'ONORDER' # Item type
9527: '-1' # -1 is "On order", but avaialable for holds
9528: 'Z'  # Collection code. CCODE
952o: '' # Koha full call number

# Get the callnumber from the record
callnumber_field: 852
callnumber_subfield: h

### OR Don't add items at all
# Possible values: 1 or 0. If set to 1, all item-related settings above will
# be ignored.
skip_items: 1
